use_frameworks!

platform :ios, '9.0'

target 'LicensesKit_Example' do
  pod 'LicensesKit', :path => '../'

  target 'LicensesKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
